In [1]:
from bs4 import BeautifulSoup
import requests
# Here, we're just importing both Beautiful Soup and the Requests library
# page_linkELA = ("https://coinmarketcap.com/currencies/elastos/historical-data/?start=20130428&end=20190212")
# page_linkKCS = ("https://coinmarketcap.com/currencies/kucoin-shares/historical-data/?start=20130428&end=20190212")
# page_linkWAN = ("https://coinmarketcap.com/currencies/wanchain/historical-data/?start=20130428&end=20190212")
page_linkVET = ("https://coinmarketcap.com/currencies/vechain/historical-data/?start=20130428&end=20190214")
page_linkTUSD = ("https://coinmarketcap.com/currencies/trueusd/historical-data/?start=20130428&end=20190214")
page_linkXVG = ("https://coinmarketcap.com/currencies/verge/historical-data/?start=20130428&end=20190214")
page_linkAE = ("https://coinmarketcap.com/currencies/aeternity/historical-data/?start=20130428&end=20190214")
page_linkSTRAT = ("https://coinmarketcap.com/currencies/stratis/historical-data/?start=20130428&end=20190214")
page_linkLRC = ("https://coinmarketcap.com/currencies/loopring/historical-data/?start=20130428&end=20190214")
page_linkAOA = ("https://coinmarketcap.com/currencies/aurora/historical-data/?start=20130428&end=20190214")
page_linkQNT = ("https://coinmarketcap.com/currencies/quant/historical-data/?start=20130428&end=20190214")

# this is the url that we've already determined is safe and legal to scrape from.
# page_responseELA = requests.get(page_linkELA, timeout=5)
# page_responseKCS= requests.get(page_linkKCS, timeout=5)
# page_responseWAN= requests.get(page_linkWAN, timeout=5)
page_responseVET= requests.get(page_linkVET, timeout=5)
page_responseTUSD= requests.get(page_linkTUSD, timeout=5)
page_responseXVG= requests.get(page_linkXVG, timeout=5)
page_responseAE= requests.get(page_linkAE, timeout=5)
page_responseSTRAT= requests.get(page_linkSTRAT, timeout=5)
page_responseLRC= requests.get(page_linkLRC, timeout=5)
page_responseAOA= requests.get(page_linkAOA, timeout=5)
page_responseQNT= requests.get(page_linkQNT, timeout=5)

# here, we fetch the content from the url, using the requests library
# page_contentELA = BeautifulSoup(page_responseELA.content, "html.parser")
# page_contentKCS = BeautifulSoup(page_responseKCS.content, "html.parser")
# page_contentWAN= BeautifulSoup(page_responseWAN.content, "html.parser")
page_contentVET= BeautifulSoup(page_responseVET.content, "html.parser")
page_contentTUSD= BeautifulSoup(page_responseTUSD.content, "html.parser")
page_contentXVG= BeautifulSoup(page_responseXVG.content, "html.parser")
page_contentAE= BeautifulSoup(page_responseAE.content, "html.parser")
page_contentSTRAT= BeautifulSoup(page_responseSTRAT.content, "html.parser")
page_contentLRC= BeautifulSoup(page_responseLRC.content, "html.parser")
page_contentAOA= BeautifulSoup(page_responseAOA.content, "html.parser")
page_contentQNT= BeautifulSoup(page_responseQNT.content, "html.parser")

#we use the html parser to parse the url content and store it in a variable.






"""

Elastos (ELA) bills itself as the 'first completely safe and decentralized infrastructure for the internet'. 
Its vision is to create a blockchain-powered decentralized internet that enables digital rights and secure 
transactions. Elastos uses the Internet as the base-layer infrastructure and separates network communications 
from application computing. It prohibits apps from directly accessing the network so as to prevent malicious attacks. 
Elastos is merged mined with Bitcoin to optimize energy efficiency and leverage the security of the Bitcoin network 
for Elastos applications. Sidechains are also included as an additional layer of security.


Kucoin Shares (KCS) is an exchange based token and native currency of the 
Kucoin crypto exchange. Holders of the token are able to reap the rewards 
from the success of the exchange as 50% of its overall trading fee revenue is shared with 
holders through the tokens. Rewards, received in the form of dividends, are proportionate 
to the amount of Kucoin Shares one holds.

Wanchain (WAN) aims to build a 'super financial market' by connecting distinct digital assets. 
Its key features are cross-chain interoperability, privacy, and smart contract functionality. 
Wanchain connects and facilitates the transfer of value between different blockchains in a 
distributed fashion. Public or private blockchains can integrate with Wanchain to establish connections 
between different ledgers and perform inter-ledger asset transfers. The Wanchain ledger supports not only 
smart contracts, but also token exchange privacy protection. Use cases of the Wanchain include asset transfers, 
loan origination, and credit payments. Wanchain is part of the Enterprise Ethereum Alliance (EEA) and Blockchain 
Interoperability Alliance (BIA). The latter comprises ICON, Aion, and Wanchain and has the shared goal of promoting 
interconnectivity between isolated blockchain networks.


"""

"\n\nElastos (ELA) bills itself as the 'first completely safe and decentralized infrastructure for the internet'. \nIts vision is to create a blockchain-powered decentralized internet that enables digital rights and secure \ntransactions. Elastos uses the Internet as the base-layer infrastructure and separates network communications \nfrom application computing. It prohibits apps from directly accessing the network so as to prevent malicious attacks. \nElastos is merged mined with Bitcoin to optimize energy efficiency and leverage the security of the Bitcoin network \nfor Elastos applications. Sidechains are also included as an additional layer of security.\n\n\nKucoin Shares (KCS) is an exchange based token and native currency of the \nKucoin crypto exchange. Holders of the token are able to reap the rewards \nfrom the success of the exchange as 50% of its overall trading fee revenue is shared with \nholders through the tokens. Rewards, received in the form of dividends, are proportionate \nto the amount of Kucoin Shares one holds.\n\nWanchain (WAN) aims to build a 'super financial market' by connecting distinct digital assets. \nIts key features are cross-chain interoperability, privacy, and smart contract functionality. \nWanchain connects and facilitates the transfer of value between different blockchains in a \ndistributed fashion. Public or private blockchains can integrate with Wanchain to establish connections \nbetween different ledgers and perform inter-ledger asset transfers. The Wanchain ledger supports not only \nsmart contracts, but also token exchange privacy protection. Use cases of the Wanchain include asset transfers, \nloan origination, and credit payments. Wanchain is part of the Enterprise Ethereum Alliance (EEA) and Blockchain \nInteroperability Alliance (BIA). The latter comprises ICON, Aion, and Wanchain and has the shared goal of promoting \ninterconnectivity between isolated blockchain networks.\n\n\n"

In [2]:
VETcontent = page_contentVET.findAll('tr')
TUSDcontent = page_contentTUSD.findAll('tr')
XVGcontent = page_contentXVG.findAll('tr')
AEcontent = page_contentAE.findAll('tr')
STRATcontent = page_contentSTRAT.findAll('tr')
LRCcontent = page_contentLRC.findAll('tr')
AOAcontent = page_contentAOA.findAll('tr')
QNTcontent = page_contentQNT.findAll('tr')

In [3]:
listofhistoricaldataVET= []
for point in range(len(VETcontent)):
    listofhistoricaldataVET.append(VETcontent[point].text)

listofhistoricaldataTUSD= []
for point in range(len(TUSDcontent)):
    listofhistoricaldataTUSD.append(TUSDcontent[point].text)

listofhistoricaldataXVG= []
for point in range(len(XVGcontent)):
    listofhistoricaldataXVG.append(XVGcontent[point].text)

listofhistoricaldataAE= []
for point in range(len(AEcontent)):
    listofhistoricaldataAE.append(AEcontent[point].text)


listofhistoricaldataSTRAT= []
for point in range(len(STRATcontent)):
    listofhistoricaldataSTRAT.append(STRATcontent[point].text)
    
    
listofhistoricaldataLRC= []
for point in range(len(LRCcontent)):
    listofhistoricaldataLRC.append(LRCcontent[point].text)

listofhistoricaldataAOA= []
for point in range(len(AOAcontent)):
    listofhistoricaldataAOA.append(AOAcontent[point].text)

listofhistoricaldataQNT= []
for point in range(len(QNTcontent)):
    listofhistoricaldataQNT.append(QNTcontent[point].text)
    
# listofhistoricaldataELA= []
# for point in range(len(ELAcontent)):
#     listofhistoricaldataELA.append(ELAcontent[point].text)
    
# listofhistoricaldataKCS= []
# for point in range(len(KCScontent)):
#     listofhistoricaldataKCS.append(KCScontent[point].text)
    
# listofhistoricaldataWAN= []
# for point in range(len(WANcontent)):
#     listofhistoricaldataWAN.append(WANcontent[point].text)

In [4]:
listofhistoricaldataVET

['\nDate\nOpen*\nHigh\nLow\nClose**\nVolume\nMarket Cap\n',
 '\nFeb 13, 2019\n0.003937\n0.003976\n0.003859\n0.003876\n3,182,996\n214,919,064\n',
 '\nFeb 12, 2019\n0.003921\n0.003950\n0.003843\n0.003924\n3,227,572\n217,588,784\n',
 '\nFeb 11, 2019\n0.004048\n0.004048\n0.003908\n0.003909\n3,260,261\n216,769,109\n',
 '\nFeb 10, 2019\n0.004022\n0.004131\n0.003939\n0.004044\n5,229,670\n224,236,626\n',
 '\nFeb 09, 2019\n0.003982\n0.004019\n0.003900\n0.004006\n3,591,370\n222,158,015\n',
 '\nFeb 08, 2019\n0.003693\n0.004055\n0.003656\n0.003966\n5,403,796\n219,930,760\n',
 '\nFeb 07, 2019\n0.003640\n0.003762\n0.003626\n0.003694\n3,386,472\n204,868,148\n',
 '\nFeb 06, 2019\n0.003774\n0.003784\n0.003620\n0.003637\n4,506,774\n201,682,749\n',
 '\nFeb 05, 2019\n0.003820\n0.003852\n0.003757\n0.003786\n4,009,846\n209,969,687\n',
 '\nFeb 04, 2019\n0.003865\n0.003876\n0.003786\n0.003827\n3,435,089\n212,240,113\n',
 '\nFeb 03, 2019\n0.003937\n0.003949\n0.003830\n0.003864\n2,778,666\n214,289,699\n',
 '\nFeb 02, 2019\n0.003917\n0.003952\n0.003866\n0.003952\n2,829,236\n219,142,902\n',
 '\nFeb 01, 2019\n0.003910\n0.003957\n0.003817\n0.003928\n3,570,933\n217,801,451\n',
 '\nJan 31, 2019\n0.004024\n0.004069\n0.003823\n0.003909\n6,030,416\n216,756,030\n',
 '\nJan 30, 2019\n0.003915\n0.004112\n0.003861\n0.004038\n4,808,429\n223,915,159\n',
 '\nJan 29, 2019\n0.003949\n0.004009\n0.003777\n0.003906\n4,799,851\n216,610,838\n',
 '\nJan 28, 2019\n0.004175\n0.004181\n0.003796\n0.003934\n7,382,324\n218,186,086\n',
 '\nJan 27, 2019\n0.004385\n0.004385\n0.004071\n0.004165\n6,486,434\n230,992,788\n',
 '\nJan 26, 2019\n0.004342\n0.004427\n0.004342\n0.004377\n4,879,760\n242,701,241\n',
 '\nJan 25, 2019\n0.004417\n0.004436\n0.004304\n0.004347\n4,715,534\n241,034,601\n',
 '\nJan 24, 2019\n0.004403\n0.004449\n0.004258\n0.004410\n6,306,102\n244,570,928\n',
 '\nJan 23, 2019\n0.004569\n0.004582\n0.004318\n0.004391\n9,733,085\n243,483,582\n',
 '\nJan 22, 2019\n0.004129\n0.004575\n0.004117\n0.004568\n14,820,175\n253,317,355\n',
 '\nJan 21, 2019\n0.004019\n0.004234\n0.004017\n0.004130\n6,977,052\n229,017,737\n',
 '\nJan 20, 2019\n0.004123\n0.004243\n0.003915\n0.004012\n5,761,503\n222,470,882\n',
 '\nJan 19, 2019\n0.004086\n0.004256\n0.004062\n0.004138\n5,533,946\n229,468,602\n',
 '\nJan 18, 2019\n0.004260\n0.004286\n0.004009\n0.004076\n6,375,463\n226,035,211\n',
 '\nJan 17, 2019\n0.004006\n0.004323\n0.003951\n0.004262\n11,020,121\n236,373,282\n',
 '\nJan 16, 2019\n0.003942\n0.004008\n0.003894\n0.003994\n4,977,149\n221,473,436\n',
 '\nJan 15, 2019\n0.004055\n0.004071\n0.003892\n0.003929\n3,254,718\n217,906,652\n',
 '\nJan 14, 2019\n0.003785\n0.004084\n0.003785\n0.004043\n5,054,733\n224,223,809\n',
 '\nJan 13, 2019\n0.004013\n0.004044\n0.003750\n0.003785\n5,438,369\n209,906,510\n',
 '\nJan 12, 2019\n0.004003\n0.004093\n0.003992\n0.004020\n4,474,792\n222,935,969\n',
 '\nJan 11, 2019\n0.004058\n0.004130\n0.003935\n0.004006\n6,509,319\n222,129,977\n',
 '\nJan 10, 2019\n0.004793\n0.004903\n0.003881\n0.004068\n13,071,386\n225,613,575\n',
 '\nJan 09, 2019\n0.004385\n0.004803\n0.004382\n0.004770\n12,107,280\n264,492,240\n',
 '\nJan 08, 2019\n0.004169\n0.004514\n0.004089\n0.004382\n7,026,686\n243,013,235\n',
 '\nJan 07, 2019\n0.004351\n0.004373\n0.004159\n0.004176\n5,226,528\n231,586,621\n',
 '\nJan 06, 2019\n0.004081\n0.004414\n0.004038\n0.004340\n5,957,396\n240,682,223\n',
 '\nJan 05, 2019\n0.004093\n0.004154\n0.004067\n0.004074\n4,724,992\n225,920,130\n',
 '\nJan 04, 2019\n0.004054\n0.004133\n0.003991\n0.004094\n4,357,275\n227,022,231\n',
 '\nJan 03, 2019\n0.004238\n0.004245\n0.003999\n0.004051\n4,319,409\n224,651,393\n',
 '\nJan 02, 2019\n0.004148\n0.004252\n0.004056\n0.004231\n5,331,171\n234,644,707\n',
 '\nJan 01, 2019\n0.003980\n0.004155\n0.003846\n0.004145\n4,902,158\n229,862,439\n',
 '\nDec 31, 2018\n0.004225\n0.004240\n0.003932\n0.003972\n5,785,271\n220,275,849\n',
 '\nDec 30, 2018\n0.004159\n0.004279\n0.004116\n0.004218\n5,549,174\n233,909,929\n',
 '\nDec 29, 2018\n0.004400\n0.004447\n0.004155\n0.004155\n6,145,706\n230,412,802\n',
 '\nDec 28, 2018\n0.003927\n0.004486\n0.003866\n0.004379\n6,489,024\n242,824,511\n',
 '\nDec 27, 2018\n0.004414\n0.004438\n0.003911\n0.003921\n5,732,771\n217,438,212\n',
 '\nDec 26, 2018\n0.004384\n0.004549\n0.004268\n0.004405\n4,614,862\n244,301,414\n',
 '\nDec 25, 2018\n0.004806\n0.004808\n0.004204\n0.004378\n7,209,293\n242,801,035\n',
 '\nDec 24, 2018\n0.004714\n0.005338\n0.004714\n0.004795\n11,846,499\n265,902,201\n',
 '\nDec 23, 2018\n0.004638\n0.004893\n0.004629\n0.004722\n6,711,658\n261,831,442\n',
 '\nDec 22, 2018\n0.004466\n0.004710\n0.004335\n0.004638\n7,190,146\n257,211,078\n',
 '\nDec 21, 2018\n0.004568\n0.004935\n0.004329\n0.004476\n11,186,891\n248,191,482\n',
 '\nDec 20, 2018\n0.004185\n0.004608\n0.004160\n0.004575\n9,315,862\n253,700,545\n',
 '\nDec 19, 2018\n0.004176\n0.004531\n0.004115\n0.004220\n10,218,552\n234,035,560\n',
 '\nDec 18, 2018\n0.004033\n0.004142\n0.003794\n0.004137\n7,001,588\n229,430,751\n',
 '\nDec 17, 2018\n0.003422\n0.004104\n0.003414\n0.004032\n9,844,028\n223,571,284\n',
 '\nDec 16, 2018\n0.003359\n0.003491\n0.003359\n0.003420\n3,574,675\n189,666,037\n',
 '\nDec 15, 2018\n0.003382\n0.003424\n0.003282\n0.003360\n3,104,697\n186,332,346\n',
 '\nDec 14, 2018\n0.003536\n0.003545\n0.003323\n0.003379\n4,710,616\n187,394,752\n',
 '\nDec 13, 2018\n0.003743\n0.003747\n0.003488\n0.003528\n4,683,647\n195,628,846\n',
 '\nDec 12, 2018\n0.003722\n0.003811\n0.003643\n0.003729\n6,205,460\n206,791,314\n',
 '\nDec 11, 2018\n0.003828\n0.003870\n0.003669\n0.003730\n4,198,655\n206,830,595\n',
 '\nDec 10, 2018\n0.004070\n0.004107\n0.003772\n0.003833\n5,930,515\n212,564,615\n',
 '\nDec 09, 2018\n0.003905\n0.004184\n0.003875\n0.004070\n6,597,735\n225,711,914\n',
 '\nDec 08, 2018\n0.003922\n0.004095\n0.003742\n0.003907\n7,447,191\n216,678,473\n',
 '\nDec 07, 2018\n0.004138\n0.004138\n0.003668\n0.003920\n12,882,281\n217,386,690\n',
 '\nDec 06, 2018\n0.004458\n0.004833\n0.004112\n0.004112\n10,483,262\n228,029,381\n',
 '\nDec 05, 2018\n0.004625\n0.004670\n0.004397\n0.004433\n7,530,496\n245,837,074\n',
 '\nDec 04, 2018\n0.004534\n0.004903\n0.004420\n0.004607\n7,610,618\n255,496,373\n',
 '\nDec 03, 2018\n0.004932\n0.004948\n0.004447\n0.004542\n7,566,014\n251,881,069\n',
 '\nDec 02, 2018\n0.005054\n0.005195\n0.004833\n0.004923\n7,230,608\n272,996,726\n',
 '\nDec 01, 2018\n0.004784\n0.005215\n0.004665\n0.005066\n7,244,018\n280,955,759\n',
 '\nNov 30, 2018\n0.005329\n0.005338\n0.004539\n0.004767\n10,048,523\n264,340,786\n',
 '\nNov 29, 2018\n0.005271\n0.005691\n0.004993\n0.005316\n11,329,440\n294,809,089\n',
 '\nNov 28, 2018\n0.004416\n0.005500\n0.004416\n0.005242\n15,663,000\n290,697,047\n',
 '\nNov 27, 2018\n0.004311\n0.004498\n0.004146\n0.004421\n7,394,600\n245,175,364\n',
 '\nNov 26, 2018\n0.004670\n0.004825\n0.004153\n0.004334\n8,320,570\n240,356,902\n',
 '\nNov 25, 2018\n0.004519\n0.004815\n0.003956\n0.004687\n8,739,310\n259,903,587\n',
 '\nNov 24, 2018\n0.005159\n0.005296\n0.004414\n0.004524\n6,614,770\n250,896,629\n',
 '\nNov 23, 2018\n0.005231\n0.005278\n0.004962\n0.005164\n8,181,900\n286,358,823\n',
 '\nNov 22, 2018\n0.005806\n0.005872\n0.005262\n0.005262\n7,453,420\n291,796,160\n',
 '\nNov 21, 2018\n0.005338\n0.005964\n0.005207\n0.005799\n12,096,500\n321,584,780\n',
 '\nNov 20, 2018\n0.006028\n0.006311\n0.005013\n0.005296\n17,991,200\n293,679,957\n',
 '\nNov 19, 2018\n0.007656\n0.007674\n0.005894\n0.006034\n19,730,300\n334,588,361\n',
 '\nNov 18, 2018\n0.007708\n0.007788\n0.007587\n0.007662\n9,844,660\n424,901,387\n',
 '\nNov 17, 2018\n0.007719\n0.007727\n0.007471\n0.007700\n10,458,300\n427,014,213\n',
 '\nNov 16, 2018\n0.007944\n0.008062\n0.007589\n0.007722\n10,133,600\n428,233,662\n',
 '\nNov 15, 2018\n0.008406\n0.008635\n0.007137\n0.007974\n13,486,900\n442,194,392\n',
 '\nNov 14, 2018\n0.009146\n0.009275\n0.007634\n0.008370\n16,750,100\n464,173,321\n',
 '\nNov 13, 2018\n0.009875\n0.009902\n0.009241\n0.009241\n12,894,700\n512,463,859\n',
 '\nNov 12, 2018\n0.010164\n0.010211\n0.009849\n0.009885\n9,464,180\n548,176,154\n',
 '\nNov 11, 2018\n0.010282\n0.010295\n0.010034\n0.010142\n8,536,240\n562,421,920\n',
 '\nNov 10, 2018\n0.010193\n0.010412\n0.010145\n0.010275\n6,509,090\n569,775,218\n',
 '\nNov 09, 2018\n0.010480\n0.010514\n0.010097\n0.010189\n12,693,000\n565,006,111\n',
 '\nNov 08, 2018\n0.010823\n0.010847\n0.010441\n0.010494\n11,530,500\n581,947,532\n',
 '\nNov 07, 2018\n0.011230\n0.011293\n0.010615\n0.010816\n17,036,100\n599,809,503\n',
 '\nNov 06, 2018\n0.010672\n0.011207\n0.010598\n0.011204\n17,164,700\n618,348,020\n',
 '\nNov 05, 2018\n0.010679\n0.010861\n0.010483\n0.010663\n15,306,500\n591,319,383\n',
 '\nNov 04, 2018\n0.010346\n0.010922\n0.010263\n0.010656\n17,269,200\n590,931,200\n',
 '\nNov 03, 2018\n0.010405\n0.010440\n0.010256\n0.010339\n10,536,500\n573,357,594\n',
 '\nNov 02, 2018\n0.010450\n0.010535\n0.010361\n0.010413\n12,214,900\n577,450,153\n',
 '\nNov 01, 2018\n0.010376\n0.010772\n0.010108\n0.010470\n13,223,800\n580,633,255\n',
 '\nOct 31, 2018\n0.010219\n0.010491\n0.010029\n0.010365\n13,609,200\n574,771,690\n',
 '\nOct 30, 2018\n0.010513\n0.010623\n0.010065\n0.010191\n13,505,500\n565,155,839\n',
 '\nOct 29, 2018\n0.010962\n0.011240\n0.010368\n0.010496\n16,595,900\n582,036,260\n',
 '\nOct 28, 2018\n0.010927\n0.011262\n0.010877\n0.010965\n12,409,700\n608,055,622\n',
 '\nOct 27, 2018\n0.011079\n0.011109\n0.010842\n0.010888\n11,666,700\n603,802,243\n',
 '\nOct 26, 2018\n0.011304\n0.011324\n0.010952\n0.011099\n12,566,800\n615,519,829\n',
 '\nOct 25, 2018\n0.011380\n0.011457\n0.011075\n0.011308\n9,122,190\n627,065,505\n',
 '\nOct 24, 2018\n0.011713\n0.011878\n0.011389\n0.011389\n14,333,200\n631,573,975\n',
 '\nOct 23, 2018\n0.011055\n0.011995\n0.010797\n0.011750\n23,224,300\n651,609,770\n',
 '\nOct 22, 2018\n0.011324\n0.011414\n0.010988\n0.011068\n11,878,700\n613,767,459\n',
 '\nOct 21, 2018\n0.011499\n0.011702\n0.011300\n0.011353\n11,968,200\n629,577,604\n',
 '\nOct 20, 2018\n0.011462\n0.011646\n0.011418\n0.011494\n15,957,400\n637,407,813\n',
 '\nOct 19, 2018\n0.011400\n0.011542\n0.011298\n0.011454\n8,150,200\n635,200,714\n',
 '\nOct 18, 2018\n0.011732\n0.011862\n0.011316\n0.011396\n8,611,690\n631,962,158\n',
 '\nOct 17, 2018\n0.011778\n0.011882\n0.011650\n0.011744\n9,594,690\n651,238,224\n',
 '\nOct 16, 2018\n0.011793\n0.012040\n0.011654\n0.011847\n7,772,460\n656,983,334\n',
 '\nOct 15, 2018\n0.011345\n0.012237\n0.011198\n0.011783\n17,371,300\n653,423,140\n',
 '\nOct 14, 2018\n0.011456\n0.011707\n0.011319\n0.011360\n7,932,190\n629,976,878\n',
 '\nOct 13, 2018\n0.011542\n0.011674\n0.011400\n0.011481\n6,564,870\n636,675,810\n',
 '\nOct 12, 2018\n0.011154\n0.011730\n0.011059\n0.011562\n9,936,260\n641,167,644\n',
 '\nOct 11, 2018\n0.013245\n0.013302\n0.011153\n0.011229\n16,074,400\n622,717,853\n',
 '\nOct 10, 2018\n0.013566\n0.013639\n0.013083\n0.013281\n11,145,500\n736,516,515\n',
 '\nOct 09, 2018\n0.013681\n0.013758\n0.013390\n0.013595\n8,453,330\n753,912,665\n',
 '\nOct 08, 2018\n0.013094\n0.013851\n0.012992\n0.013666\n10,593,600\n757,827,769\n',
 '\nOct 07, 2018\n0.013016\n0.013111\n0.012874\n0.013076\n4,508,570\n725,131,658\n',
 '\nOct 06, 2018\n0.013122\n0.013229\n0.012933\n0.012996\n4,673,320\n720,673,097\n',
 '\nOct 05, 2018\n0.012834\n0.013213\n0.012779\n0.013110\n7,337,180\n727,000,482\n',
 '\nOct 04, 2018\n0.012768\n0.012953\n0.012749\n0.012826\n10,516,100\n711,240,247\n',
 '\nOct 03, 2018\n0.012946\n0.012982\n0.012618\n0.012764\n12,731,200\n707,851,962\n',
 '\nOct 02, 2018\n0.012805\n0.013353\n0.012786\n0.012994\n17,676,800\n720,562,188\n',
 '\nOct 01, 2018\n0.012888\n0.013100\n0.012672\n0.012804\n12,615,600\n710,042,424\n',
 '\nSep 30, 2018\n0.013073\n0.013119\n0.012708\n0.012891\n14,573,700\n714,883,623\n',
 '\nSep 29, 2018\n0.013049\n0.013098\n0.012715\n0.013052\n14,815,500\n723,795,199\n',
 '\nSep 28, 2018\n0.013086\n0.013594\n0.012994\n0.013047\n15,868,800\n723,512,379\n',
 '\nSep 27, 2018\n0.012531\n0.013197\n0.012436\n0.013078\n17,120,600\n725,259,204\n',
 '\nSep 26, 2018\n0.012788\n0.012939\n0.012396\n0.012554\n16,953,400\n696,162,104\n',
 '\nSep 25, 2018\n0.013123\n0.013123\n0.012171\n0.012803\n19,622,300\n709,981,424\n',
 '\nSep 24, 2018\n0.013912\n0.013990\n0.012918\n0.013123\n18,296,700\n727,754,667\n',
 '\nSep 23, 2018\n0.013740\n0.014086\n0.013616\n0.013945\n11,897,700\n773,321,822\n',
 '\nSep 22, 2018\n0.014388\n0.014583\n0.013459\n0.013666\n14,838,600\n757,866,588\n',
 '\nSep 21, 2018\n0.013702\n0.014614\n0.013469\n0.014389\n36,111,400\n797,965,906\n',
 '\nSep 20, 2018\n0.013008\n0.013687\n0.012933\n0.013630\n18,295,500\n755,864,672\n',
 '\nSep 19, 2018\n0.012991\n0.013254\n0.012500\n0.013005\n17,267,900\n721,199,917\n',
 '\nSep 18, 2018\n0.012732\n0.013238\n0.012415\n0.012956\n16,694,600\n718,454,908\n',
 '\nSep 17, 2018\n0.014159\n0.014324\n0.012430\n0.012725\n20,636,200\n705,650,409\n',
 '\nSep 16, 2018\n0.014267\n0.014335\n0.013821\n0.014170\n10,220,600\n785,771,410\n',
 '\nSep 15, 2018\n0.013958\n0.014609\n0.013754\n0.014275\n14,368,600\n791,627,430\n',
 '\nSep 14, 2018\n0.014089\n0.014358\n0.013534\n0.013978\n16,430,800\n775,118,556\n',
 '\nSep 13, 2018\n0.013835\n0.014357\n0.013275\n0.014060\n28,222,000\n779,704,662\n',
 '\nSep 12, 2018\n0.013163\n0.013991\n0.011735\n0.013835\n25,123,900\n767,210,710\n',
 '\nSep 11, 2018\n0.014237\n0.014284\n0.012823\n0.013121\n18,847,600\n727,621,575\n',
 '\nSep 10, 2018\n0.014565\n0.015371\n0.013830\n0.014124\n22,846,400\n783,237,129\n',
 '\nSep 09, 2018\n0.014637\n0.015326\n0.014176\n0.014490\n18,117,700\n803,528,016\n',
 '\nSep 08, 2018\n0.015631\n0.016219\n0.014365\n0.014644\n19,308,600\n812,084,682\n',
 '\nSep 07, 2018\n0.016133\n0.016769\n0.015261\n0.015675\n27,829,600\n869,280,695\n',
 '\nSep 06, 2018\n0.016262\n0.016329\n0.015057\n0.016142\n36,930,400\n895,166,966\n',
 '\nSep 05, 2018\n0.019446\n0.019740\n0.016192\n0.016192\n49,983,300\n897,923,066\n',
 '\nSep 04, 2018\n0.018778\n0.019775\n0.018590\n0.019471\n37,147,400\n1,079,748,050\n',
 '\nSep 03, 2018\n0.017853\n0.019222\n0.017412\n0.018753\n29,578,300\n1,039,948,187\n',
 '\nSep 02, 2018\n0.018144\n0.018394\n0.017387\n0.017815\n21,871,100\n987,931,646\n',
 '\nSep 01, 2018\n0.017106\n0.018581\n0.016999\n0.018176\n28,300,500\n1,007,961,896\n',
 '\nAug 31, 2018\n0.017229\n0.017558\n0.016626\n0.017143\n29,320,200\n950,677,155\n',
 '\nAug 30, 2018\n0.016953\n0.017341\n0.015660\n0.017341\n26,699,000\n961,618,374\n',
 '\nAug 29, 2018\n0.017981\n0.018113\n0.016611\n0.016924\n36,464,600\n938,504,841\n',
 '\nAug 28, 2018\n0.017839\n0.018756\n0.017549\n0.017979\n45,607,800\n997,048,404\n',
 '\nAug 27, 2018\n0.015222\n0.017855\n0.015210\n0.017823\n53,968,100\n988,397,466\n',
 '\nAug 26, 2018\n0.015390\n0.015446\n0.014512\n0.015233\n20,503,900\n844,719,793\n',
 '\nAug 25, 2018\n0.014552\n0.015735\n0.014244\n0.015413\n24,453,700\n854,712,737\n',
 '\nAug 24, 2018\n0.014743\n0.014743\n0.013981\n0.014535\n19,980,000\n806,056,752\n',
 '\nAug 23, 2018\n0.013686\n0.014784\n0.013629\n0.014674\n31,250,400\n813,737,233\n',
 '\nAug 22, 2018\n0.015461\n0.016250\n0.012490\n0.013787\n67,288,000\n764,576,611\n',
 '\nAug 21, 2018\n0.012951\n0.015805\n0.012951\n0.015389\n49,710,400\n853,387,368\n',
 '\nAug 20, 2018\n0.014275\n0.014877\n0.013032\n0.013057\n38,838,000\n724,061,381\n',
 '\nAug 19, 2018\n0.012711\n0.014422\n0.012263\n0.014374\n36,557,300\n797,111,903\n',
 '\nAug 18, 2018\n0.014950\n0.014950\n0.011119\n0.012732\n49,994,400\n706,027,502\n',
 '\nAug 17, 2018\n0.011227\n0.015232\n0.010868\n0.015031\n94,427,600\n833,556,755\n',
 '\nAug 16, 2018\n0.007899\n0.011601\n0.007744\n0.011221\n51,160,900\n622,279,761\n',
 '\nAug 15, 2018\n0.007768\n0.008747\n0.007663\n0.007891\n22,410,600\n437,592,758\n',
 '\nAug 14, 2018\n0.007204\n0.007736\n0.006116\n0.007736\n22,264,400\n429,015,019\n',
 '\nAug 13, 2018\n0.009090\n0.009201\n0.006960\n0.007168\n16,989,000\n397,515,621\n',
 '\nAug 12, 2018\n0.009195\n0.009752\n0.009024\n0.009080\n8,428,220\n503,522,892\n',
 '\nAug 11, 2018\n0.009682\n0.009753\n0.008724\n0.009192\n12,731,100\n509,765,986\n',
 '\nAug 10, 2018\n0.011666\n0.012135\n0.009460\n0.009747\n36,278,100\n540,526,727\n',
 '\nAug 09, 2018\n0.010761\n0.012022\n0.010316\n0.011683\n32,613,700\n647,872,121\n',
 '\nAug 08, 2018\n0.012858\n0.013021\n0.010402\n0.010776\n22,236,100\n597,558,040\n',
 '\nAug 07, 2018\n0.013315\n0.014457\n0.012163\n0.012899\n21,022,400\n715,321,715\n',
 '\nAug 06, 2018\n0.013963\n0.014308\n0.012930\n0.013424\n18,774,100\n744,440,996\n',
 '\nAug 05, 2018\n0.013428\n0.014295\n0.012696\n0.014081\n19,746,000\n780,858,121\n',
 '\nAug 04, 2018\n0.015218\n0.015944\n0.012377\n0.013333\n27,059,500\n739,350,252\n',
 '\nAug 03, 2018\n0.015041\n0.015730\n0.014938\n0.015307\n46,250,600\n848,840,080\n',
 '\n\nVeChain Price\n\n\n\n0.003862\nUSD\n\n\n',
 '\n\nMarket Rank\n\n\n#25\n\n',
 '\n\nMarket Cap\n\n\n\n214,145,891\nUSD\n\n\n',
 '\n\n24h Volume\n\n\n\n2,814,170\nUSD\n\n\n',
 '\n\nCirculating Supply\n\n\n\n55,454,734,800\n\nVET\n\n',
 '\n\nTotal Supply\n\n\n\n86,712,634,466\n\nVET\n\n',
 '\n\nMax Supply\n\n\nNo Data\n\n',
 "\n\nYesterday's Open / Close\n\n\n$0.003937 USD\n/\n$0.003876 USD\n\n",
 "\n\nYesterday's High / Low\n\n\n$0.003976 USD\n/\n$0.003859 USD\n\n",
 "\n\nYesterday's Change\n\n\n-6.1e-05 USD (-1.56%)\n\n",
 "\n\nYesterday's Volume\n\n\n$3,182,996 USD\n\n"]

In [5]:
newsymbols= ['VET', 'TUSD', 'XVG', 'AE', 'AOA', 'QNT', 'STRAT', "LRC"]

In [6]:
dataLRC= []
for a in listofhistoricaldataLRC:
    dataLRC.append(a.split('\n'))

dataSTRAT= []
for a in listofhistoricaldataSTRAT:
    dataSTRAT.append(a.split('\n'))
    
dataQNT= []
for a in listofhistoricaldataQNT:
    dataQNT.append(a.split('\n'))

dataQNT= []
for a in listofhistoricaldataQNT:
    dataQNT.append(a.split('\n'))

dataAOA= []
for a in listofhistoricaldataAOA:
    dataAOA.append(a.split('\n'))

dataAE= []
for a in listofhistoricaldataAE:
    dataAE.append(a.split('\n'))

dataXVG= []
for a in listofhistoricaldataXVG:
    dataXVG.append(a.split('\n'))

dataTUSD= []
for a in listofhistoricaldataTUSD:
    dataTUSD.append(a.split('\n'))

dataVET= []
for a in listofhistoricaldataVET:
    dataVET.append(a.split('\n'))

# dataELA= []
# for a in listofhistoricaldataELA:
#     dataELA.append(a.split('\n'))

# dataKCS= []
# for a in listofhistoricaldataKCS:
#     dataKCS.append(a.split('\n'))
    
# dataWAN= []
# for a in listofhistoricaldataWAN:
#     dataWAN.append(a.split('\n'))

In [7]:
newsymbols

['VET', 'TUSD', 'XVG', 'AE', 'AOA', 'QNT', 'STRAT', 'LRC']

In [8]:
import pandas as pd

PandadataframeVET= pd.DataFrame(dataVET) 
PandadataframeTUSD= pd.DataFrame(dataTUSD) 
PandadataframeXVG= pd.DataFrame(dataXVG) 
PandadataframeAE= pd.DataFrame(dataAE) 
PandadataframeAOA= pd.DataFrame(dataAOA) 
PandadataframeQNT= pd.DataFrame(dataQNT) 
PandadataframeSTRAT= pd.DataFrame(dataSTRAT) 
PandadataframeLRC= pd.DataFrame(dataLRC)


# PandadataframeELA= pd.DataFrame(dataELA) 
# PandadataframeKCS= pd.DataFrame(dataKCS)
# PandadataframeWAN= pd.DataFrame(dataWAN)

In [9]:
newsymbols

['VET', 'TUSD', 'XVG', 'AE', 'AOA', 'QNT', 'STRAT', 'LRC']

In [10]:
PandadataframeLRC

,0,1,2,3,4,5,6,7,8,9,10
0,,Date,Open*,High,Low,Close**,Volume,Market Cap,,None,None
1,,"Feb 13, 2019",0.053778,0.054505,0.053050,0.053468,"906,239","42,185,329",,None,None
2,,"Feb 12, 2019",0.053781,0.054004,0.053102,0.053773,"764,100","42,425,924",,None,None
3,,"Feb 11, 2019",0.055186,0.055490,0.053467,0.053827,"990,393","42,468,467",,None,None
4,,"Feb 10, 2019",0.054593,0.055479,0.052695,0.055287,"1,016,308","43,620,761",,None,None
5,,"Feb 09, 2019",0.055369,0.055817,0.053497,0.054550,"891,573","43,039,378",,None,None
6,,"Feb 08, 2019",0.051758,0.056250,0.051421,0.055106,"959,711","43,478,079",,None,None
7,,"Feb 07, 2019",0.051393,0.053210,0.051219,0.051812,"594,906","40,878,705",,None,None
8,,"Feb 06, 2019",0.053982,0.054017,0.050852,0.051325,"859,487","40,494,690",,None,None
9,,"Feb 05, 2019",0.054999,0.055202,0.053696,0.053886,"610,118","42,515,506",,None,None
10,,"Feb 04, 2019",0.056346,0.056429,0.054930,0.055130,"823,650","43,496,938",,None,None
11,,"Feb 03, 2019",0.056893,0.058822,0.056048,0.056396,"1,068,557","44,495,852",,None,None
12,,"Feb 02, 2019",0.057263,0.058469,0.055220,0.056983,"936,028","44,958,410",,None,None
13,,"Feb 01, 2019",0.055043,0.061340,0.052931,0.057745,"1,566,584","45,560,253",,None,None
14,,"Jan 31, 2019",0.059428,0.060096,0.054221,0.055044,"892,443","43,428,748",,None,None
15,,"Jan 30, 2019",0.059878,0.059993,0.058224,0.059410,"1,173,718","46,873,225",,None,None
16,,"Jan 29, 2019",0.059692,0.064780,0.057215,0.059766,"2,490,158","47,154,753",,None,None
17,,"Jan 28, 2019",0.068368,0.068368,0.056217,0.059490,"2,147,431","46,937,009",,None,None
18,,"Jan 27, 2019",0.073047,0.073219,0.066020,0.068405,"2,401,757","53,970,633",,None,None
19,,"Jan 26, 2019",0.077084,0.078334,0.072375,0.072996,"1,505,266","57,592,842",,None,None
20,,"Jan 25, 2019",0.080313,0.083518,0.076058,0.077150,"2,167,065","60,870,401",,None,None
21,,"Jan 24, 2019",0.086003,0.086165,0.079170,0.080563,"2,839,466","63,562,987",,None,None
22,,"Jan 23, 2019",0.104890,0.104890,0.084042,0.085669,"7,027,299","67,591,399",,None,None
23,,"Jan 22, 2019",0.068994,0.107928,0.065992,0.103905,"33,074,631","81,979,754",,None,None
24,,"Jan 21, 2019",0.068216,0.072558,0.066157,0.069157,"9,888,851","54,564,018",,None,None
25,,"Jan 20, 2019",0.068865,0.070114,0.061262,0.068019,"4,407,828","53,665,825",,None,None
26,,"Jan 19, 2019",0.063497,0.073335,0.063251,0.069249,"10,300,895","54,636,670",,None,None
27,,"Jan 18, 2019",0.059113,0.066456,0.052235,0.062944,"8,967,225","49,661,755",,None,None
28,,"Jan 17, 2019",0.049469,0.063104,0.049469,0.058103,"10,473,230","45,842,092",,None,None
29,,"Jan 16, 2019",0.041269,0.050413,0.041217,0.049242,"3,511,774","38,851,512",,None,None
...,...,...,...,...,...,...,...,...,...,...,...
515,,"Sep 17, 2017",0.051722,0.054201,0.045282,0.047464,"41,447","33,108,084",,None,None
516,,"Sep 16, 2017",0.054674,0.060583,0.044989,0.051594,"64,551","35,989,056",,None,None
517,,"Sep 15, 2017",0.041509,0.059085,0.037998,0.054253,"75,715","37,843,600",,None,None
518,,"Sep 14, 2017",0.047730,0.050915,0.041044,0.041946,"106,674","29,258,651",,None,None
519,,"Sep 13, 2017",0.050891,0.050891,0.043732,0.046747,"177,864","32,608,159",,None,None
520,,"Sep 12, 2017",0.044543,0.052202,0.042257,0.050735,"316,986","35,389,801",,None,None
521,,"Sep 11, 2017",0.045290,0.046290,0.042939,0.044576,"1,042,710","31,093,595",,None,None
522,,"Sep 10, 2017",0.047409,0.047487,0.042998,0.045183,"1,592,970","31,516,791",,None,None
523,,"Sep 09, 2017",0.047309,0.049558,0.046045,0.047638,"2,811,530","33,229,665",,None,None
524,,"Sep 08, 2017",0.057744,0.059996,0.043617,0.047308,"7,482,910","32,999,408",,None,None
525,,"Sep 07, 2017",0.044223,0.065158,0.042396,0.059468,"3,608,710","41,481,261",,None,None
526,,"Sep 06, 2017",0.037334,0.045799,0.034961,0.044460,"2,589,560","31,012,750",,None,None
527,,"Sep 05, 2017",0.035629,0.044912,0.027952,0.037301,"2,816,840","26,019,075",,None,None
528,,"Sep 04, 2017",0.084437,0.086526,0.031562,0.035719,"3,792,200","24,915,640",,None,None
529,,"Sep 03, 2017",0.062124,0.111949,0.059038,0.084183,"9,833,750","58,720,774",,None,None
530,,"Sep 02, 2017",0.075317,0.075590,0.049599,0.060716,"2,840,680","42,351,789",,None,None
531,,"Sep 01, 2017",0.133504,0.135884,0.070038,0.075265,"8,198,750",-,,None,None
532,,"Aug 31, 2017",0.104805,0.133921,0.082414,0.133323,"66,809",-,,None,None
533,,"Aug 30, 2017",0.118854,0.176763,0.076650,0.104810,"200,829",-,,None,None
534,,,Loopring Price,,,,0.059550,USD,,,
535,,,Market Rank,,,#73,,,None,None,None
536,,,Market Cap,,,,"46,984,211",USD,,,
537,,,24h Volume,,,,"4,303,359",USD,,,
538,,,Circulating Supply,,,,"788,984,491",,LRC,,
539,,,Total Supply,,,,"1,374,955,752",,LRC,,
540,,,Max Supply,,,No Data,,,None,None,None
541,,,Yesterday's Open / Close,,,$0.053778 USD,/,$0.053468 USD,,,None
542,,,Yesterday's High / Low,,,$0.054505 USD,/,$0.053050 USD,,,None
543,,,Yesterday's Change,,,-0.00031 USD (-0.58%),,,None,None,None
544,,,Yesterday's Volume,,,"$906,239 USD",,,None,None,None

In [11]:
#drops the end/blank data points at the end of the dataframe
dfVETformatted = PandadataframeVET.drop([x for x in range(196,206)])
dfTUSDformatted = PandadataframeTUSD.drop([x for x in range(328,357)])
dfXVGformatted = PandadataframeXVG.drop([x for x in range(328,1585)])
dfAEformatted = PandadataframeAE.drop([x for x in range(328,635)])
dfAOAformatted = PandadataframeAOA.drop([x for x in range(234,245)])
dfQNTformatted = PandadataframeQNT.drop([x for x in range(189, len(PandadataframeQNT))])
dfSTRATformatted = PandadataframeSTRAT.drop([x for x in range(328, len(PandadataframeSTRAT))])
dfLRCformatted = PandadataframeLRC.drop([x for x in range(328, len(PandadataframeLRC))])


# dfWANformatted = PandadataframeWAN.drop([x for x in range(327,338)])
# dfKCSformatted = PandadataframeKCS.drop([x for x in range(477,488)])


#drops the last three columns with no data associated
dfVETformatted = dfVETformatted.drop(dfVETformatted.columns[[8, 9, 10]], axis=1)
dfTUSDformatted = dfTUSDformatted.drop(dfTUSDformatted.columns[[8, 9, 10]], axis=1)
dfXVGformatted = dfXVGformatted.drop(dfXVGformatted.columns[[8, 9, 10]], axis=1)
dfAOAformatted = dfAOAformatted.drop(dfAOAformatted.columns[[8, 9, 10]], axis=1)
dfAEformatted = dfAEformatted.drop(dfAEformatted.columns[[8, 9, 10]], axis=1)
dfQNTformatted = dfQNTformatted.drop(dfQNTformatted.columns[[8, 9, 10]], axis=1)
dfSTRATformatted = dfSTRATformatted.drop(dfSTRATformatted.columns[[8, 9, 10]], axis=1)
dfLRCformatted = dfLRCformatted.drop(dfLRCformatted.columns[[8, 9, 10]], axis=1)




# dfWANformatted = dfWANformatted.drop(dfWANformatted.columns[[8, 9, 10]], axis=1)
# dfKCSformatted = dfKCSformatted.drop(dfKCSformatted.columns[[8, 9, 10]], axis=1)

#renames the columns and drops the top row
dfVETformatted.rename(columns=dfVETformatted.iloc[0])#.drop(dfVETformatted.index[0])
dfTUSDformatted.rename(columns=dfTUSDformatted.iloc[0])#.drop(dfTUSDformatted.index[0])
dfXVGformatted.rename(columns=dfXVGformatted.iloc[0])#.drop(dfXVGformatted.index[0])
dfAOAformatted.rename(columns=dfAOAformatted.iloc[0])#.drop(dfAOAformatted.index[0])
dfAEformatted.rename(columns=dfAEformatted.iloc[0])#.drop(dfAEformatted.index[0])
dfQNTformatted.rename(columns=dfQNTformatted.iloc[0])#.drop(dfQNTformatted.index[0])
dfSTRATformatted.rename(columns=dfSTRATformatted.iloc[0])#.drop(dfSTRATformatted.index[0])
dfLRCformatted.rename(columns=dfLRCformatted.iloc[0])#.drop(dfLRCformatted.index[0])



# dfWANformatted.rename(columns=dfWANformatted.iloc[0]).drop(dfWANformatted.index[0])
# dfKCSformatted.rename(columns=dfKCSformatted.iloc[0]).drop(dfKCSformatted.index[0])

dfVEThistorical = dfVETformatted.rename(columns=dfVETformatted.iloc[0])#.drop(([x for x in range(0,3)]))
dfTUSDhistorical = dfTUSDformatted.rename(columns=dfTUSDformatted.iloc[0])#.drop(([x for x in range(0,3)]))
dfXVGhistorical = dfXVGformatted.rename(columns=dfXVGformatted.iloc[0])#.drop(([x for x in range(0,3)]))
dfAOAhistorical = dfAOAformatted.rename(columns=dfAOAformatted.iloc[0])#.drop(([x for x in range(0,3)]))
dfAEhistorical = dfAEformatted.rename(columns=dfAEformatted.iloc[0])#.drop(([x for x in range(0,3)]))
dfQNThistorical = dfQNTformatted.rename(columns=dfQNTformatted.iloc[0])#.drop(([x for x in range(0,3)]))
dfSTRAThistorical = dfSTRATformatted.rename(columns=dfSTRATformatted.iloc[0])#.drop(([x for x in range(0,3)]))
dfLRChistorical = dfLRCformatted.rename(columns=dfLRCformatted.iloc[0])#.drop(([x for x in range(0,3)]))



# dfWANhistorical = dfWANformatted.rename(columns=dfWANformatted.iloc[0]).drop(dfWANformatted.index[0])
# dfKCShistorical = dfKCSformatted.rename(columns=dfKCSformatted.iloc[0]).drop(dfKCSformatted.index[0])

In [14]:
dfLRChistorical.head()

,,Date,Open*,High,Low,Close**,Volume,Market Cap
0,,Date,Open*,High,Low,Close**,Volume,Market Cap
1,,"Feb 13, 2019",0.053778,0.054505,0.053050,0.053468,"906,239","42,185,329"
2,,"Feb 12, 2019",0.053781,0.054004,0.053102,0.053773,"764,100","42,425,924"
3,,"Feb 11, 2019",0.055186,0.055490,0.053467,0.053827,"990,393","42,468,467"
4,,"Feb 10, 2019",0.054593,0.055479,0.052695,0.055287,"1,016,308","43,620,761"

In [15]:
dfLRChistorical.to_csv("LRC.csv")

In [16]:
dfQNThistorical.to_csv("QNT.csv")

In [17]:
dfSTRAThistorical.to_csv("STRAT.csv")

In [18]:
dfAOAhistorical.to_csv("AOA.csv")

In [19]:
dfAEhistorical.to_csv("AE.csv")

In [20]:
dfXVGhistorical.to_csv("XVG.csv")

In [21]:
dfVEThistorical.to_csv("VET.csv")

In [22]:
dfTUSDhistorical.to_csv("TUSD.csv")

In [23]:
dfTUSDhistorical

,,Date,Open*,High,Low,Close**,Volume,Market Cap
0,,Date,Open*,High,Low,Close**,Volume,Market Cap
1,,"Feb 13, 2019",1.02,1.02,1.01,1.01,"47,129,353","209,025,309"
2,,"Feb 12, 2019",1.01,1.02,1.01,1.02,"60,256,778","209,422,339"
3,,"Feb 11, 2019",1.02,1.02,1.01,1.01,"38,129,351","209,428,397"
4,,"Feb 10, 2019",1.01,1.02,1.01,1.02,"45,775,593","207,220,126"
5,,"Feb 09, 2019",1.01,1.02,1.01,1.01,"48,370,217","207,296,930"
6,,"Feb 08, 2019",1.01,1.02,1.00,1.01,"89,362,717","207,556,522"
7,,"Feb 07, 2019",1.01,1.01,1.01,1.01,"30,327,998","207,545,490"
8,,"Feb 06, 2019",1.01,1.02,1.01,1.01,"56,699,075","207,687,737"
9,,"Feb 05, 2019",1.01,1.02,1.01,1.01,"36,259,478","208,020,488"
10,,"Feb 04, 2019",1.01,1.02,1.01,1.01,"34,509,169","208,569,743"
11,,"Feb 03, 2019",1.01,1.02,1.01,1.01,"34,914,547","209,608,306"
12,,"Feb 02, 2019",1.02,1.02,1.01,1.01,"35,543,272","209,207,500"
13,,"Feb 01, 2019",1.01,1.02,1.01,1.02,"51,872,546","210,253,797"
14,,"Jan 31, 2019",1.01,1.02,1.01,1.01,"47,708,948","210,027,598"
15,,"Jan 30, 2019",1.01,1.02,1.01,1.01,"51,707,770","210,144,442"
16,,"Jan 29, 2019",1.01,1.01,1.01,1.01,"56,293,508","209,822,228"
17,,"Jan 28, 2019",1.01,1.02,1.01,1.01,"83,036,170","211,497,096"
18,,"Jan 27, 2019",1.01,1.02,1.01,1.01,"53,463,015","211,690,805"
19,,"Jan 26, 2019",1.01,1.01,1.01,1.01,"36,389,003","211,524,979"
20,,"Jan 25, 2019",1.01,1.01,1.01,1.01,"37,679,544","211,878,886"
21,,"Jan 24, 2019",1.01,1.01,1.01,1.01,"38,756,232","209,405,534"
22,,"Jan 23, 2019",1.01,1.01,1.01,1.01,"45,721,202","209,523,952"
23,,"Jan 22, 2019",1.01,1.02,1.01,1.01,"46,751,835","209,364,314"
24,,"Jan 21, 2019",1.01,1.02,1.01,1.01,"41,830,787","210,393,743"
25,,"Jan 20, 2019",1.01,1.03,1.01,1.02,"51,671,705","211,630,538"
26,,"Jan 19, 2019",1.01,1.02,1.00,1.01,"49,687,423","210,386,637"
27,,"Jan 18, 2019",1.01,1.02,1.01,1.01,"42,777,356","210,812,867"
28,,"Jan 17, 2019",1.01,1.02,1.01,1.01,"65,094,518","210,468,720"
29,,"Jan 16, 2019",1.02,1.02,1.01,1.01,"61,075,577","210,595,914"
...,...,...,...,...,...,...,...,...
298,,"Apr 22, 2018",1.00,1.01,0.985880,0.998857,"1,184,730","9,761,944"
299,,"Apr 21, 2018",0.989886,1.01,0.987937,1.01,"1,920,660","9,857,457"
300,,"Apr 20, 2018",1.01,1.01,0.984619,0.991088,"1,856,480","9,686,017"
301,,"Apr 19, 2018",1.01,1.01,0.990650,0.998710,"1,474,770","9,760,507"
302,,"Apr 18, 2018",0.999774,1.02,0.986373,1.00,"1,883,270","9,823,715"
303,,"Apr 17, 2018",0.998573,1.01,0.990441,0.994880,"1,665,870","9,733,025"
304,,"Apr 16, 2018",1.00,1.01,0.994757,0.998114,"2,861,680","9,764,664"
305,,"Apr 15, 2018",1.01,1.02,0.993790,1.00,"3,089,420","9,603,749"
306,,"Apr 14, 2018",1.01,1.02,0.986084,1.01,"3,937,500","9,661,475"
307,,"Apr 13, 2018",1.01,1.02,0.995964,1.01,"2,514,640","9,626,518"
308,,"Apr 12, 2018",1.01,1.03,0.994800,1.01,"3,940,870","9,621,545"
309,,"Apr 11, 2018",0.999510,1.01,0.994931,1.01,"803,442","9,663,623"
310,,"Apr 10, 2018",1.01,1.01,0.995461,0.999562,"816,891","9,558,926"
311,,"Apr 09, 2018",1.01,1.02,0.996886,1.01,"1,364,890","9,644,975"
312,,"Apr 08, 2018",1.01,1.02,0.999721,1.01,"617,041","9,655,303"
313,,"Apr 07, 2018",1.01,1.02,0.934734,1.01,"802,142","9,641,995"
314,,"Apr 06, 2018",1.01,1.02,0.996298,1.01,"867,908","9,666,984"
315,,"Apr 05, 2018",1.00,1.02,0.990475,1.01,"1,245,700","9,667,367"
316,,"Apr 04, 2018",1.00,1.02,0.992784,1.00,"1,664,350","9,605,709"
317,,"Apr 03, 2018",0.998044,1.01,0.989415,1.00,"1,527,120","9,491,073"
318,,"Apr 02, 2018",1.01,1.01,0.991269,0.997387,"1,017,440","9,449,359"
319,,"Apr 01, 2018",1.00,1.02,0.992281,1.01,"2,178,630","9,533,423"
320,,"Mar 31, 2018",1.00,1.01,0.993513,1.00,"1,613,600","9,478,473"
321,,"Mar 30, 2018",1.01,1.02,0.986757,0.994400,"3,017,020","9,421,060"
322,,"Mar 29, 2018",1.00,1.01,0.978259,1.01,"2,985,780","7,989,885"
323,,"Mar 28, 2018",0.992560,1.02,0.986810,1.00,"951,963","7,926,175"
324,,"Mar 27, 2018",0.998520,1.02,0.989418,0.999424,"2,200,920","7,919,550"
325,,"Mar 26, 2018",0.994993,1.01,0.982498,1.00,"2,587,900","7,931,801"
326,,"Mar 25, 2018",0.990601,1.01,0.987590,0.995833,"825,428","7,891,095"
327,,"Mar 24, 2018",1.00,1.01,0.987376,0.998900,"967,029","7,915,398"

In [6]:
!pip install nbmerge
!pip install nbmerge

nbmerge BottomthreeCryptos.ipynb Crypto.ipynb > merged.ipynb

SyntaxError: invalid syntax (<ipython-input-6-944b607d4367>, line 4)

In [2]:
!pip install alpha_vantage

Requirement already satisfied: alpha_vantage in /anaconda3/lib/python3.7/site-packages (2.1.0)
Requirement already satisfied: requests in /anaconda3/lib/python3.7/site-packages (from alpha_vantage) (2.21.0)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (2.8)

In [59]:
import alpha_vantage
%matplotlib inline
from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.cryptocurrencies import CryptoCurrencies
import matplotlib
import matplotlib.pyplot as plt
#importing the required tools for alpha advantage api

apikey = 'JJXIFEPV0N66DTON'
#apikey obtained through alpha vantage website

In [55]:
#alpha vantage api syntax, requiring a function, symbol and market
#using the api key to access api, resulted in output being a pandas dataframe
cc = CryptoCurrencies(key=apikey, output_format='pandas')
data, meta_data = cc.get_digital_currency_daily(symbol='XRP', market='USD')

In [45]:
bitcoin_meta

{'1. Information': 'Daily Prices and Volumes for Digital Currency',
 '2. Digital Currency Code': 'BTC',
 '3. Digital Currency Name': 'Bitcoin',
 '4. Market Code': 'USD',
 '5. Market Name': 'United States Dollar',
 '6. Last Refreshed': '2019-02-11 (end of day)',
 '7. Time Zone': 'UTC'}

In [49]:
bitcoin_data.head()

,1a. open (USD),1b. open (USD),2a. high (USD),2b. high (USD),3a. low (USD),3b. low (USD),4a. close (USD),4b. close (USD),5. volume,6. market cap (USD)
date,,,,,,,,,,
2014-04-01,468.480106,468.480106,491.267273,491.267273,468.480106,468.480106,479.023434,479.023434,62894.683068,3.012803e+07
2014-04-02,479.679615,479.679615,494.111337,494.111337,430.725909,430.725909,438.377824,438.377824,96314.587552,4.222218e+07
2014-04-03,437.322089,437.322089,452.441405,452.441405,414.811104,414.811104,446.819755,446.819755,74292.749549,3.319547e+07
2014-04-04,448.597144,448.597144,457.327172,457.327172,429.184117,429.184117,451.645992,451.645992,39267.667348,1.773508e+07
2014-04-05,450.027798,450.027798,466.385470,466.385470,445.107783,445.107783,464.379322,464.379322,21574.144537,1.001859e+07

In [53]:
ethereum_meta

{'1. Information': 'Daily Prices and Volumes for Digital Currency',
 '2. Digital Currency Code': 'ETH',
 '3. Digital Currency Name': 'Ethereum',
 '4. Market Code': 'USD',
 '5. Market Name': 'United States Dollar',
 '6. Last Refreshed': '2019-02-11 (end of day)',
 '7. Time Zone': 'UTC'}

In [54]:
ethereum_data.head()

,1a. open (USD),1b. open (USD),2a. high (USD),2b. high (USD),3a. low (USD),3b. low (USD),4a. close (USD),4b. close (USD),5. volume,6. market cap (USD)
date,,,,,,,,,,
2015-08-08,3.00000,3.00000,3.00000,3.00000,0.15000,0.15000,1.19999,1.19999,1942.888147,2331.446348
2015-08-09,1.19999,1.19999,1.19999,1.19999,1.19999,1.19999,1.19999,1.19999,0.000000,0.000000
2015-08-10,1.19999,1.19999,1.19999,1.19999,1.19999,1.19999,1.19999,1.19999,0.000000,0.000000
2015-08-11,1.19999,1.19999,1.19999,1.19999,0.65038,0.65038,0.99000,0.99000,9234.568705,9142.223018
2015-08-12,0.99000,0.99000,1.28800,1.28800,0.90500,0.90500,1.28800,1.28800,1736.114983,2236.116098

In [57]:
xrp_meta

{'1. Information': 'Daily Prices and Volumes for Digital Currency',
 '2. Digital Currency Code': 'XRP',
 '3. Digital Currency Name': 'Ripple',
 '4. Market Code': 'USD',
 '5. Market Name': 'United States Dollar',
 '6. Last Refreshed': '2019-02-11 (end of day)',
 '7. Time Zone': 'UTC'}

In [58]:
xrp_data.head()

,1a. open (USD),1b. open (USD),2a. high (USD),2b. high (USD),3a. low (USD),3b. low (USD),4a. close (USD),4b. close (USD),5. volume,6. market cap (USD)
date,,,,,,,,,,
2014-04-09,0.009407,0.009407,0.009407,0.009407,0.008333,0.008333,0.008333,0.008333,1658.399999,13.820000
2014-04-10,0.008333,0.008333,0.008333,0.008333,0.006796,0.006796,0.006796,0.006796,10037.029375,68.216000
2014-04-11,0.006796,0.006796,0.006983,0.006983,0.006727,0.006727,0.006727,0.006727,184.338400,1.240000
2014-04-12,0.006727,0.006727,0.006893,0.006893,0.006727,0.006727,0.006880,0.006880,7965.670792,54.803000
2014-04-13,0.006880,0.006880,0.006880,0.006880,0.006515,0.006515,0.006515,0.006515,91.700000,0.597468