In [63]:
import pandas as pd

In [73]:
ELA_reshaped = pd.read_csv("ELA")
KCS_reshaped = pd.read_csv("KCS")
WAN_reshaped = pd.read_csv("WAN")

In [74]:
ELA_reshaped = ELA_reshaped.drop(ELA_reshaped.index[326:]).drop(ELA_reshaped.index[0])

In [75]:
KCS_reshaped = KCS_reshaped.drop(KCS_reshaped.index[326:]).drop(KCS_reshaped.index[0])

In [77]:
WAN_reshaped = WAN_reshaped.drop(WAN_reshaped.index[0])

In [67]:
ELA_reshaped.head()

,Unnamed: 0,Date,Open*,High,Low,Close**,Volume,Market Cap,Close Percent Change
1,1,"Feb 11, 2019",2.34,2.36,2.23,2.25,"825,674","32,779,845",0.056338
2,2,"Feb 10, 2019",2.28,2.39,2.20,2.36,"1,038,737","34,322,470",0.048889
3,3,"Feb 09, 2019",2.30,2.32,2.21,2.28,"503,749","33,125,031",-0.033898
4,4,"Feb 08, 2019",2.13,2.32,2.10,2.30,"1,124,742","33,426,019",0.008772
5,5,"Feb 07, 2019",2.11,2.15,2.07,2.11,"408,356","30,614,038",-0.082609

In [68]:
KCS_reshaped.head()

,Unnamed: 0,Date,Open*,High,Low,Close**,Volume,Market Cap,Close Percent Change
1,1,"Feb 11, 2019",0.372457,0.372965,0.357386,0.360186,"74,144","32,395,108",0.033865
2,2,"Feb 10, 2019",0.373908,0.376798,0.366396,0.370683,"113,364","33,339,198",0.029143
3,3,"Feb 09, 2019",0.367814,0.376134,0.364795,0.373724,"77,250","33,612,734",0.008204
4,4,"Feb 08, 2019",0.349097,0.370431,0.341340,0.368694,"136,393","33,160,299",-0.013459
5,5,"Feb 07, 2019",0.353000,0.354022,0.344373,0.348911,"31,603","31,380,985",-0.053657

In [78]:
WAN_reshaped

,Unnamed: 0,Date,Open*,High,Low,Close**,Volume,Market Cap,Close Percent Change
1,1,"Feb 11, 2019",0.292928,0.296669,0.287315,0.293568,"1,349,269","31,163,022",-0.005855
2,2,"Feb 10, 2019",0.290055,0.292139,0.284831,0.291913,"1,253,091","30,987,283",-0.005638
3,3,"Feb 09, 2019",0.292845,0.293144,0.283931,0.289930,"1,423,044","30,776,796",-0.006793
4,4,"Feb 08, 2019",0.273142,0.296012,0.267220,0.292698,"1,809,122","31,070,595",0.009547
5,5,"Feb 07, 2019",0.282813,0.286318,0.270510,0.272198,"1,910,097","28,894,489",-0.070038
6,6,"Feb 06, 2019",0.263348,0.283880,0.252161,0.282607,"2,936,422","29,999,417",0.038241
7,7,"Feb 05, 2019",0.271795,0.272879,0.261297,0.262837,"1,384,802","27,900,758",-0.069956
8,8,"Feb 04, 2019",0.272061,0.277935,0.271110,0.272426,"1,083,242","28,918,676",0.036483
9,9,"Feb 03, 2019",0.275564,0.278519,0.270018,0.271510,"933,561","28,821,508",-0.003362
10,10,"Feb 02, 2019",0.275846,0.277837,0.272373,0.275765,"930,973","29,273,114",0.015672
11,11,"Feb 01, 2019",0.276701,0.279454,0.265337,0.276280,"1,252,366","29,327,794",0.001868
12,12,"Jan 31, 2019",0.289539,0.293779,0.271358,0.275208,"1,445,003","29,214,064",-0.003880
13,13,"Jan 30, 2019",0.287506,0.299162,0.283805,0.289559,"1,736,488","30,737,440",0.052146
14,14,"Jan 29, 2019",0.294685,0.296450,0.282187,0.287700,"1,906,991","30,540,100",-0.006420
15,15,"Jan 28, 2019",0.315164,0.315178,0.284640,0.294712,"2,238,805","31,284,424",0.024373
16,16,"Jan 27, 2019",0.339741,0.339741,0.310417,0.315689,"2,371,675","33,511,161",0.071178
17,17,"Jan 26, 2019",0.323167,0.341044,0.319757,0.339270,"2,197,630","36,014,402",0.074697
18,18,"Jan 25, 2019",0.328584,0.331175,0.319004,0.322996,"2,086,160","34,286,824",-0.047968
19,19,"Jan 24, 2019",0.319036,0.328851,0.316838,0.327835,"1,848,851","34,800,509",0.014982
20,20,"Jan 23, 2019",0.334538,0.335009,0.314018,0.319276,"2,629,553","33,891,992",-0.026108
21,21,"Jan 22, 2019",0.321198,0.335728,0.316843,0.334467,"3,463,644","35,504,475",0.047580
22,22,"Jan 21, 2019",0.313804,0.319311,0.308510,0.319311,"3,193,040","33,895,651",-0.045314
23,23,"Jan 20, 2019",0.344018,0.346702,0.309135,0.313367,"3,500,974","33,264,727",-0.018615
24,24,"Jan 19, 2019",0.328628,0.354335,0.328628,0.344229,"3,546,370","36,540,742",0.098485
25,25,"Jan 18, 2019",0.336602,0.347053,0.323151,0.327014,"3,934,895","34,713,338",-0.050010
26,26,"Jan 17, 2019",0.315861,0.347906,0.315202,0.335115,"6,065,371","35,573,344",0.024773
27,27,"Jan 16, 2019",0.293488,0.324109,0.292815,0.315723,"3,990,372","33,514,755",-0.057867
28,28,"Jan 15, 2019",0.306128,0.309767,0.288058,0.293815,"2,572,976","31,189,219",-0.069390
29,29,"Jan 14, 2019",0.288071,0.309833,0.288071,0.305728,"2,647,709","32,453,746",0.040546
30,30,"Jan 13, 2019",0.311283,0.316459,0.284934,0.287404,"2,665,451","30,508,683",-0.059936
...,...,...,...,...,...,...,...,...,...
297,297,"Apr 21, 2018",6.62,6.640000,5.980000,6.20,"15,093,900","658,273,899",-0.018987
298,298,"Apr 20, 2018",6.55,6.630000,6.110000,6.63,"20,524,400","704,254,913",0.069355
299,299,"Apr 19, 2018",5.96,6.610000,5.850000,6.56,"27,065,400","696,323,198",-0.010558
300,300,"Apr 18, 2018",5.38,6.070000,5.370000,5.97,"15,311,000","633,455,446",-0.089939
301,301,"Apr 17, 2018",5.67,5.700000,5.350000,5.38,"20,658,700","571,426,299",-0.098827
302,302,"Apr 16, 2018",5.98,6.100000,5.550000,5.68,"22,110,000","602,609,655",0.055762
303,303,"Apr 15, 2018",5.65,6.190000,5.650000,5.98,"20,248,200","635,128,409",0.052817
304,304,"Apr 14, 2018",5.63,6.350000,5.420000,5.63,"30,017,000","597,650,210",-0.058528
305,305,"Apr 13, 2018",5.96,6.880000,5.590000,5.74,"62,270,800","608,908,744",0.019538
306,306,"Apr 12, 2018",4.36,6.250000,4.340000,6.04,"41,240,700","641,458,283",0.052265
307,307,"Apr 11, 2018",4.48,4.690000,4.310000,4.37,"28,904,700","463,971,315",-0.276490
308,308,"Apr 10, 2018",3.71,4.480000,3.670000,4.48,"27,672,800","475,100,342",0.025172
309,309,"Apr 09, 2018",3.90,3.990000,3.520000,3.69,"13,151,900","392,055,124",-0.176339
310,310,"Apr 08, 2018",3.58,3.980000,3.580000,3.92,"15,045,700",-,0.062331
311,311,"Apr 07, 2018",3.03,3.820000,3.020000,3.59,"23,856,100",-,-0.084184
312,312,"Apr 06, 2018",3.15,3.220000,3.000000,3.02,"5,182,220",-,-0.158774
313,313,"Apr 05, 2018",3.03,3.200000,2.980000,3.17,"4,778,540",-,0.049669
314,314,"Apr 04, 2018",3.54,3.540000,3.020000,3.04,"6,714,370",-,-0.041009
315,315,"Apr 03, 2018",3.20,3.530000,3.130000,3.52,"7,611,090",-,0.157895
316,316,"Apr 02, 2018",3.08,3.300000,3.030000,3.19,"5,889,880",-,-0.093750
317,317,"Apr 01, 2018",3.27,3.300000,2.870000,3.08,"6,716,460",-,-0.034483
318,318,"Mar 31, 2018",3.28,3.450000,3.180000,3.27,"11,831,300",-,0.061688
319,319,"Mar 30, 2018",2.94,3.380000,2.750000,3.29,"14,111,200",-,0.006116
320,320,"Mar 29, 2018",3.42,3.580000,2.890000,2.96,"14,919,000",-,-0.100304
321,321,"Mar 28, 2018",3.34,3.530000,3.270000,3.42,"9,226,000",-,0.155405
322,322,"Mar 27, 2018",3.76,3.840000,3.250000,3.35,"11,789,300",-,-0.020468
323,323,"Mar 26, 2018",4.16,4.210000,3.360000,3.80,"20,263,900",-,0.134328
324,324,"Mar 25, 2018",4.12,4.310000,4.090000,4.15,"11,426,400",-,0.092105
325,325,"Mar 24, 2018",4.25,4.820000,4.190000,4.19,"35,446,300",-,0.009639
326,326,NaN,Yesterday's Volume,NaN,NaN,"$1,428,150 USD",NaN,NaN,NaN

In [69]:
ELA_reshaped.to_csv("ELA_reshaped.csv")

In [70]:
KCS_reshaped.to_csv("KCS_reshaped.csv")

In [79]:
WAN_reshaped.to_csv("WAN_reshaped.csv")